// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "guyuxiang",
            "url": "https://guyuxiang.github.io",
            "email": "gu_yuxiang@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inner/chain-data-subscribe/{networkCode}/address-subscribe": {
            "post": {
                "description": "Register a contract-address log subscription based on eth_getLogs for callback processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Subscribe contract address logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contract address subscription payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressSubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data-subscribe/{networkCode}/address-subscribe-cancel": {
            "post": {
                "description": "Update or stop a contract-address log subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Cancel contract address log subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contract address subscription cancel payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressSubscribeCancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data-subscribe/{networkCode}/tx-subscribe": {
            "post": {
                "description": "Register a transaction subscription for callback processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Subscribe transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction subscription payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxSubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data-subscribe/{networkCode}/tx-subscribe-cancel": {
            "post": {
                "description": "Cancel a registered transaction subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscription"
                ],
                "summary": "Cancel transaction subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction subscription cancel payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxSubscribeCancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/address-balance": {
            "post": {
                "description": "Query native token balance of an address on the configured network",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Query address balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Address balance query payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/latest-block": {
            "post": {
                "description": "Query latest block number and timestamp from the configured network",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Query latest block",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/token-add": {
            "post": {
                "description": "Add a token definition into database-backed EVM token registry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Add or update token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token add request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/token-balance": {
            "post": {
                "description": "Query token balance of an address for a token configured in the database-backed EVM token registry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Query token balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token balance query payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/token-delete": {
            "post": {
                "description": "Delete a token definition from database-backed EVM token registry by token code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Delete token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token delete request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/token-get": {
            "post": {
                "description": "Get a token definition from database-backed EVM token registry by token code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Get token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token get request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenGetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/token-list": {
            "post": {
                "description": "List token definitions from database-backed EVM token registry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "List tokens",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token list request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/token-supply": {
            "post": {
                "description": "Query total supply of a token configured in the database-backed EVM token registry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Query token supply",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token supply query payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenSupplyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/{networkCode}/common/tx-query": {
            "post": {
                "description": "Query transaction status and decoded events by transaction hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Query transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction query payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-invoke/{networkCode}/common/tx-send": {
            "post": {
                "description": "Submit either a signed raw EVM transaction or an ERC-4337 UserOperation to the configured RPC or bundler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "Send transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Signed transaction payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/chain-invoke/{networkCode}/wallet/faucet": {
            "post": {
                "description": "Create and submit a native token transfer from the configured wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Send native token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Wallet transfer payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BalanceChargeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/contract/contract-config-push-record/push": {
            "post": {
                "description": "Create a contract configuration push record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Push contract config",
                "parameters": [
                    {
                        "description": "Contract config push payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContractConfigPushMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/inner/contract/list/{networkCode}": {
            "post": {
                "description": "Query currently applied contract configurations for the configured network",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "List current contracts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured network code",
                        "name": "networkCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/open/all-clients/contract/web3-contract-info": {
            "post": {
                "description": "Query current contract and network info for web3 clients",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "List web3 contract info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/open/ops-client/contract/contract-config-push-record/apply": {
            "post": {
                "description": "Apply a pushed contract configuration record into current contract config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Apply contract config push",
                "parameters": [
                    {
                        "description": "Apply contract push payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ApplyContractConfigPushRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        },
        "/open/ops-client/contract/contract-config-push-record/page": {
            "post": {
                "description": "Query paged contract configuration push records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Page contract config push records",
                "parameters": [
                    {
                        "description": "Contract push page query payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddressBalanceRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "models.AddressSubscribeCancelRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "endBlockNumber": {
                    "type": "integer"
                }
            }
        },
        "models.AddressSubscribeRange": {
            "type": "object",
            "properties": {
                "endBlockNumber": {
                    "type": "integer"
                },
                "startBlockNumber": {
                    "type": "integer"
                }
            }
        },
        "models.AddressSubscribeRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "subscribeRange": {
                    "$ref": "#/definitions/models.AddressSubscribeRange"
                }
            }
        },
        "models.ApplyContractConfigPushRecordRequest": {
            "type": "object",
            "properties": {
                "pushRecordCode": {
                    "type": "string"
                }
            }
        },
        "models.BalanceChargeRequest": {
            "type": "object"
        },
        "models.ContractConfigPushItem": {
            "type": "object",
            "properties": {
                "contractAbi": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "contractCode": {
                    "type": "string"
                },
                "contractDeployTxBlockNumber": {
                    "type": "integer"
                },
                "networkCode": {
                    "type": "string"
                }
            }
        },
        "models.ContractConfigPushMessage": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "pushId": {
                    "type": "string"
                },
                "pushItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ContractConfigPushItem"
                    }
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.TokenAddRequest": {
            "type": "object",
            "properties": {
                "decimals": {
                    "type": "integer"
                },
                "tokenAddress": {
                    "type": "string"
                },
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenBalanceRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenDeleteRequest": {
            "type": "object",
            "properties": {
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenGetRequest": {
            "type": "object",
            "properties": {
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenListRequest": {
            "type": "object"
        },
        "models.TokenSupplyRequest": {
            "type": "object",
            "properties": {
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TxQueryRequest": {
            "type": "object",
            "properties": {
                "txCode": {
                    "type": "string"
                }
            }
        },
        "models.TxSendRequest": {
            "type": "object",
            "properties": {
                "eip7702Auth": {
                    "type": "object",
                    "additionalProperties": true
                },
                "entryPoint": {
                    "type": "string"
                },
                "txSignResult": {
                    "type": "string"
                },
                "userOperation": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "models.TxSubscribeCancelRequest": {
            "type": "object",
            "properties": {
                "txCode": {
                    "type": "string"
                }
            }
        },
        "models.TxSubscribeRange": {
            "type": "object",
            "properties": {
                "endTimestamp": {
                    "type": "integer"
                }
            }
        },
        "models.TxSubscribeRequest": {
            "type": "object",
            "properties": {
                "subscribeRange": {
                    "$ref": "#/definitions/models.TxSubscribeRange"
                },
                "txCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger projectc-ethereum-connector",
	Description:      "This is a projectc-ethereum-connector.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
